lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem'
    public_key: '%kernel.project_dir%/config/jwt/public.pem'
    pass_phrase: 'ilyes' # Set your passphrase used during key generation
    token_ttl: 3600
    user_identity_field: email