nelmio_cors:
    defaults:
        allow_origin: ['*']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        max_age: 3600
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
        allow_credentials: false
        expose_headers: []
